In [1]:
x=10

10

In [2]:
y=20

20

In [3]:
x+y

30

In [4]:
x*y

200

In [5]:
x/y

0.5

In [6]:
x-y

-10

In [7]:
y%x

0

In [8]:
 ❄ = -12

-12

In [9]:
 ✹ = 27

27

In [10]:
 ❄ > ✹

false

In [11]:
 ❄ < ✹

true

In [12]:
π

π = 3.1415926535897...

In [13]:
π = 3.2

ErrorException: cannot assign a value to variable MathConstants.π from module Main

In [14]:
π

π = 3.1415926535897...

In [15]:
m = [1,2,3,4]

4-element Array{Int64,1}:
 1
 2
 3
 4

In [16]:
type(m)

UndefVarError: UndefVarError: type not defined

In [17]:
n = m

4-element Array{Int64,1}:
 1
 2
 3
 4

In [18]:
n

4-element Array{Int64,1}:
 1
 2
 3
 4

In [19]:
pop!(m)

4

In [20]:
pop!(m)

3

In [21]:
pop!(m)

2

In [22]:
push!(m,3)

2-element Array{Int64,1}:
 1
 3

In [23]:
m

2-element Array{Int64,1}:
 1
 3

In [24]:
push!(m,4)

3-element Array{Int64,1}:
 1
 3
 4

In [25]:
push!(m,5)

4-element Array{Int64,1}:
 1
 3
 4
 5

In [26]:
typeof(0:5)

UnitRange{Int64}

In [27]:
collect(0:10:30)

4-element Array{Int64,1}:
  0
 10
 20
 30

In [28]:
x=collect(0:1:30)
x

31-element Array{Int64,1}:
  0
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
  ⋮
 19
 20
 21
 22
 23
 24
 25
 26
 27
 28
 29
 30

In [29]:
div(5, 2) 

2

In [30]:
5 \ 35 

7.0

In [31]:
2^2 

4

In [32]:
(1 + 3) * 2

8

In [33]:
10^19

-8446744073709551616

In [34]:
3 & 5 

1

In [35]:
2 | 4 

6

In [36]:
xor(2, 4)

6

In [37]:
2 >>> 1 

1

In [38]:
2 >> 1

1

In [39]:
2 << 1

4

In [40]:
bitstring(2)

"0000000000000000000000000000000000000000000000000000000000000010"

In [41]:
bitstring(4)

"0000000000000000000000000000000000000000000000000000000000000100"

In [42]:
bitstring(xor(2, 4))

"0000000000000000000000000000000000000000000000000000000000000110"

In [43]:
1 == 1

true

In [44]:
1 != 1

false

In [45]:
1 < 10

true

In [46]:
1 > 10

false

In [47]:
2 <= 2

true

In [48]:
2 >= 2

true

In [49]:
1 < 2 < 3

true

In [50]:
2 < 3 < 2

false

In [51]:
ascii("This is a string")[1]  

'T': ASCII/Unicode U+0054 (category Lu: Letter, uppercase)

In [52]:
"good" > "bye"

true

In [53]:
"good" == "good"

true

In [54]:
"1 + 2 = 3" == "1 + 2 = $(1 + 2)" 

true

In [55]:
"2 + 2 = $(2 + 2)"

"2 + 2 = 4"

In [56]:
println("I'm Julia. Nice to meet you!")

I'm Julia. Nice to meet you!


In [57]:
using Printf
@printf "%d is less than %f\n" 4.5 5.3 

5 is less than 5.300000


In [58]:
someOtherVar =2
try
    someOtherVar 
catch e
    println(e)
end

2

In [59]:
SomeOtherVar123! = 6

6

In [60]:
2 * π 

6.283185307179586

In [61]:
a = Int64[] 

0-element Array{Int64,1}

In [62]:
a

0-element Array{Int64,1}

In [63]:
b = [4, 5, 6]

3-element Array{Int64,1}:
 4
 5
 6

In [64]:
b = [4; 5; 6] 

3-element Array{Int64,1}:
 4
 5
 6

In [65]:
b[1] 

4

In [66]:
b[end]

6

In [67]:
b[-1] 

BoundsError: BoundsError: attempt to access 3-element Array{Int64,1} at index [-1]

In [68]:
b[0] 

BoundsError: BoundsError: attempt to access 3-element Array{Int64,1} at index [0]

In [69]:
b = Int8[4, 5, 6]

3-element Array{Int8,1}:
 4
 5
 6

In [70]:
push!(a, 1)

1-element Array{Int64,1}:
 1

In [71]:
push!(a, 2)

2-element Array{Int64,1}:
 1
 2

In [72]:
push!(a, 4)

3-element Array{Int64,1}:
 1
 2
 4

In [73]:
push!(a, 3) 

4-element Array{Int64,1}:
 1
 2
 4
 3

In [74]:
append!(a, b) 

7-element Array{Int64,1}:
 1
 2
 4
 3
 4
 5
 6

In [75]:
pop!(b)

6

In [76]:
b

2-element Array{Int8,1}:
 4
 5

In [77]:
push!(b, 6)

3-element Array{Int8,1}:
 4
 5
 6

In [78]:
b

3-element Array{Int8,1}:
 4
 5
 6

In [79]:
a[1]

1

In [80]:
a[end]

6

In [81]:
popfirst!(a) 

1

In [82]:
a

6-element Array{Int64,1}:
 2
 4
 3
 4
 5
 6

In [83]:
pushfirst!(a, 7)

7-element Array{Int64,1}:
 7
 2
 4
 3
 4
 5
 6

In [84]:
a

7-element Array{Int64,1}:
 7
 2
 4
 3
 4
 5
 6

In [85]:
arr = [5,4,6]

3-element Array{Int64,1}:
 5
 4
 6

In [86]:
sort(arr)

3-element Array{Int64,1}:
 4
 5
 6

In [87]:
arr

3-element Array{Int64,1}:
 5
 4
 6

In [88]:
x=sort(arr)

3-element Array{Int64,1}:
 4
 5
 6

In [89]:
x

3-element Array{Int64,1}:
 4
 5
 6

In [90]:
x=sort!(arr)

3-element Array{Int64,1}:
 4
 5
 6

In [91]:
x

3-element Array{Int64,1}:
 4
 5
 6

In [92]:
arr = [5,4,6]

3-element Array{Int64,1}:
 5
 4
 6

In [93]:
sort!(arr)

3-element Array{Int64,1}:
 4
 5
 6

In [94]:
try
    a[0] 
    a[end + 1]
catch e
    println(e)
end

BoundsError([7, 2, 4, 3, 4, 5, 6], (0,))


In [95]:
a = [1:5;]

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [96]:
a2 = [1:5]

1-element Array{UnitRange{Int64},1}:
 1:5

In [97]:
a[1:3] 

3-element Array{Int64,1}:
 1
 2
 3

In [98]:
a[2:end]

4-element Array{Int64,1}:
 2
 3
 4
 5

In [99]:
arr = [3,4,5]

3-element Array{Int64,1}:
 3
 4
 5

In [100]:
splice!(arr, 2)

4