In [1]:
a = [1, 2, 3, 4, 5]

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [2]:
a1 = [1, 2, 3.0, 4, 5]

5-element Array{Float64,1}:
 1.0
 2.0
 3.0
 4.0
 5.0

In [3]:
a+a1

5-element Array{Float64,1}:
  2.0
  4.0
  6.0
  8.0
 10.0

In [4]:
s = ["this", "is", "an", "array", "of", "strings"]

6-element Array{String,1}:
 "this"   
 "is"     
 "an"     
 "array"  
 "of"     
 "strings"

In [5]:
trigfuns = [sin, cos, tan]

3-element Array{Function,1}:
 sin
 cos
 tan

In [6]:
array = Array{Int64}(undef, 5)

5-element Array{Int64,1}:
               0
               1
 140270726995712
               4
               1

In [7]:
array3 = Array{Int64}(undef, 2, 2, 2)

2×2×2 Array{Int64,3}:
[:, :, 1] =
 34359738373  34359738378
 34359738376  68719476751

[:, :, 2] =
  17179869201  163208757284
 124554051588             1

In [8]:
[1, "2", 3.0, sin, pi]

5-element Array{Any,1}:
  1                    
   "2"                 
  3.0                  
   sin                 
 π = 3.1415926535897...

In [9]:
typeof(ans)

Array{Any,1}

In [10]:
Int64[1, 2, 3, 4]

4-element Array{Int64,1}:
 1
 2
 3
 4

In [11]:
Int64[1, 2, 3, 4, 5, 6, 7, 8,  9, 10.1]

InexactError: InexactError: Int64(Int64, 10.1)

In [12]:
x=[1 2 3 4 ; 5 6 7 8]

2×4 Array{Int64,2}:
 1  2  3  4
 5  6  7  8

In [13]:
x

2×4 Array{Int64,2}:
 1  2  3  4
 5  6  7  8

In [14]:
 [1, 2, 3, 4, 5]

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [15]:
[1 2 3 4]

1×4 Array{Int64,2}:
 1  2  3  4

In [16]:
x = rand(5)

5-element Array{Float64,1}:
 0.649746817806852  
 0.40556606335959344
 0.01184251926235036
 0.897959019167641  
 0.58458649890583   

In [17]:
 x = rand(5, 1)

5×1 Array{Float64,2}:
 0.42519826161252894
 0.916295869162129  
 0.5278621802547045 
 0.663246006336472  
 0.6880445930036767 

In [18]:
Vector(undef, 5)

5-element Array{Any,1}:
 #undef
 #undef
 #undef
 #undef
 #undef

In [19]:
 1:10

1:10

In [20]:
for n in 1:10 
    println(n) end

1
2
3
4
5
6
7
8
9
10


In [21]:
collect(1:10)

10-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [22]:
collect(3.5:9.5)

7-element Array{Float64,1}:
 3.5
 4.5
 5.5
 6.5
 7.5
 8.5
 9.5

In [23]:
collect(0:10:100)

11-element Array{Int64,1}:
   0
  10
  20
  30
  40
  50
  60
  70
  80
  90
 100

In [24]:
collect(4:-1:1)

4-element Array{Int64,1}:
 4
 3
 2
 1

In [25]:
[1:6...]

6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6

In [26]:
range(1, length=12, stop=100)

1.0:9.0:100.0

In [27]:
range(1, stop=100, step=10)

1:10:91

In [28]:
collect(range(1, length=12, stop=100))

12-element Array{Float64,1}:
   1.0
  10.0
  19.0
  28.0
  37.0
  46.0
  55.0
  64.0
  73.0
  82.0
  91.0
 100.0

In [29]:
#exp10 function (10^x)
exp10.(range(2.0, stop=3.0, length=5))

5-element Array{Float64,1}:
  100.0             
  177.82794100389228
  316.22776601683796
  562.341325190349  
 1000.0             

In [30]:
step(range(1, length=10, stop=100))

11.0

In [31]:
collect(0:5:100)

21-element Array{Int64,1}:
   0
   5
  10
  15
  20
  25
  30
  35
  40
  45
  50
  55
  60
  65
  70
  75
  80
  85
  90
  95
 100

In [32]:
for i in collect(1:6)
    println(i)
end

1
2
3
4
5
6


In [33]:
for i in 1:6
    println(i)
end

1
2
3
4
5
6


In [34]:
[n^2 for n in 1:5]

5-element Array{Int64,1}:
  1
  4
  9
 16
 25

In [35]:
[r * c for r in 1:5, c in 1:5]

5×5 Array{Int64,2}:
 1   2   3   4   5
 2   4   6   8  10
 3   6   9  12  15
 4   8  12  16  20
 5  10  15  20  25

In [36]:
[i^2 for i=1:10  if i != 5]

9-element Array{Int64,1}:
   1
   4
   9
  16
  36
  49
  64
  81
 100

In [37]:
collect(x^2 for x in 1:10)

10-element Array{Int64,1}:
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100

In [38]:
collect(x^2 for x in 1:10 if x != 1)

9-element Array{Int64,1}:
   4
   9
  16
  25
  36
  49
  64
  81
 100

In [39]:
zeros(2, 3)

2×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0

In [40]:
zeros(Int64, 3, 5)

3×5 Array{Int64,2}:
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0

In [41]:
ones(2, 3)

2×3 Array{Float64,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0

In [42]:
rand(2, 3)

2×3 Array{Float64,2}:
 0.372614  0.680429  0.186269
 0.144323  0.13389   0.195354

In [43]:
rand(1:6, 3, 3)

3×3 Array{Int64,2}:
 1  5  5
 3  3  4
 4  5  4

In [44]:
trues(3, 4)

3×4 BitArray{2}:
 true  true  true  true
 true  true  true  true
 true  true  true  true

In [45]:
fill(42, 9)

9-element Array{Int64,1}:
 42
 42
 42
 42
 42
 42
 42
 42
 42

In [46]:
fill("hi", 2, 2)

2×2 Array{String,2}:
 "hi"  "hi"
 "hi"  "hi"

In [47]:
a = zeros(10)

10-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [48]:
fill!(a, 42)

10-element Array{Float64,1}:
 42.0
 42.0
 42.0
 42.0
 42.0
 42.0
 42.0
 42.0
 42.0
 42.0

In [49]:
trueArray = falses(3,3)

3×3 BitArray{2}:
 false  false  false
 false  false  false
 false  false  false

In [50]:
fill!(trueArray, true)

3×3 BitArray{2}:
 true  true  true
 true  true  true
 true  true  true