In [3]:
A=[2 -4 8.2; -5.5 3.5 63]

2×3 Array{Float64,2}:
  2.0  -4.0   8.2
 -5.5   3.5  63.0

In [4]:
A

2×3 Array{Float64,2}:
  2.0  -4.0   8.2
 -5.5   3.5  63.0

In [5]:
size(A)

(2, 3)

In [6]:
A[1:2,1:3]

2×3 Array{Float64,2}:
  2.0  -4.0   8.2
 -5.5   3.5  63.0

In [7]:
A[:,3]

2-element Array{Float64,1}:
  8.2
 63.0

In [8]:
A[2,:] 

3-element Array{Float64,1}:
 -5.5
  3.5
 63.0

In [9]:
A[:] 

6-element Array{Float64,1}:
  2.0
 -5.5
 -4.0
  3.5
  8.2
 63.0

In [10]:
A’[:]

LoadError: syntax: invalid character "’"

In [11]:
X = [A A; A A]

4×6 Array{Float64,2}:
  2.0  -4.0   8.2   2.0  -4.0   8.2
 -5.5   3.5  63.0  -5.5   3.5  63.0
  2.0  -4.0   8.2   2.0  -4.0   8.2
 -5.5   3.5  63.0  -5.5   3.5  63.0

In [12]:
A'

3×2 LinearAlgebra.Adjoint{Float64,Array{Float64,2}}:
  2.0  -5.5
 -4.0   3.5
  8.2  63.0

In [13]:
print([4.0 7; -10.6 89.8] + [19 -34.7; 20 1])

[23.0 -27.7; 9.4 90.8]

In [14]:
10 * [1 2; 3 4]

2×2 Array{Int64,2}:
 10  20
 30  40

In [15]:
[1 2; 3 4] + 10

MethodError: MethodError: no method matching +(::Array{Int64,2}, ::Int64)
Closest candidates are:
  +(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:502
  +(!Matched::Complex{Bool}, ::Real) at complex.jl:292
  +(!Matched::Missing, ::Number) at missing.jl:93
  ...

In [16]:
[1 2; 3 4] * [5, 6]

2-element Array{Int64,1}:
 17
 39

In [17]:
[2 4 3; 3 1 5] * [3 10; 4 2; 1 7]

2×2 Array{Int64,2}:
 25  49
 18  67

In [18]:
sum(A)

67.2

In [19]:
mean(A)

UndefVarError: UndefVarError: mean not defined

In [20]:
norm(A[:]) 

UndefVarError: UndefVarError: norm not defined

In [21]:
vecnorm(A)

UndefVarError: UndefVarError: vecnorm not defined

In [22]:
y_hat = X’*beta + v

LoadError: syntax: invalid character "’"

In [23]:
y_hat

UndefVarError: UndefVarError: y_hat not defined

In [24]:
a = [1, 2, 3] # vector
a = [1; 2; 3] # same vector
a

3-element Array{Int64,1}:
 1
 2
 3

In [25]:
a = [1, 2, 3]
b = [1 2 3]
a == b

false

In [26]:
a = collect(1.0:0.5:4)

7-element Array{Float64,1}:
 1.0
 1.5
 2.0
 2.5
 3.0
 3.5
 4.0

In [27]:
i=10
j=10
n =1
a = i:n:j # list of points from i to j with step n
a = range(1, 5, length=1000) # linearly spaced list of k points

MethodError: MethodError: no method matching range(::Int64, ::Int64; length=1000)
Closest candidates are:
  range(::Any; length, stop, step) at range.jl:76

In [28]:
collect(x for x in 1:10 if isodd(x))

5-element Array{Int64,1}:
 1
 3
 5
 7
 9

In [29]:
a = ["micro", "macro", "econometrics"];
for (index, value) in enumerate(a)
println("$index$value")
end

1micro
2macro
3econometrics


In [30]:
show(a) # shows a

["micro", "macro", "econometrics"]

In [31]:
sum(a) # sum of a

MethodError: MethodError: no method matching +(::String, ::String)
Closest candidates are:
  +(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:502

In [32]:
maximum(a) # max of a

"micro"

In [33]:
minimum(a) # min of a

"econometrics"

In [34]:
a[end] # gets last element of a

"econometrics"

In [35]:
a[end-1] # gets element of a -1

"macro"

In [36]:
a = [2,1,3]

3-element Array{Int64,1}:
 2
 1
 3

In [37]:
sort(a) # sorts a

3-element Array{Int64,1}:
 1
 2
 3

In [38]:
sort(a,by=abs) # sorts a by absolute values

3-element Array{Int64,1}:
 1
 2
 3

In [39]:
sortperm(a) # indices of sort of a

3-element Array{Int64,1}:
 2
 1
 3

In [40]:
first(a) # returns 2

2

In [41]:
last(a) # returns 3

3

In [42]:
a = [2,1,3]
first(a) # returns 2

2

In [43]:
last(a) # returns 3

3

In [44]:
findall(isodd,a) # returns indices of occurrences (here 2,3)

2-element Array{Int64,1}:
 2
 3

In [45]:
findfirst(isodd,a) # returns first index of occurrence

2

In [46]:
a = [1,2,3]

3-element Array{Int64,1}:
 1
 2
 3

In [47]:
2 in a # returns true

true

In [48]:
in(2,a) # same as above

true

In [49]:
4 in a # returns false

false

In [50]:
sort(a) # sorts a and changes it

3-element Array{Int64,1}:
 1
 2
 3

In [51]:
a

3-element Array{Int64,1}:
 1
 2
 3

In [53]:
sort!(a) # sorts a and changes it

3-element Array{Int64,1}:
 1
 2
 3

In [54]:
a

3-element Array{Int64,1}:
 1
 2
 3

In [55]:
popfirst!(a) # eliminates first element of a

1

In [56]:
pushfirst!(a,c) # adds c as an additional element of a at its start

UndefVarError: UndefVarError: c not defined

In [57]:
pop!(a) # eliminates last element of a

3

In [58]:
push!(a,c) # adds c as an additional element of a at its end

UndefVarError: UndefVarError: c not defined

In [59]:
a = [2,1,3]
b = [2,4,5]

3-element Array{Int64,1}:
 2
 4
 5

In [60]:
union(a,b) # returns 2,1,3,4,5

5-element Array{Int64,1}:
 2
 1
 3
 4
 5

In [61]:
intersect(a,b) # returns 2

1-element Array{Int64,1}:
 2

In [62]:
setdiff(a,b) # returns 1,3

2-element Array{Int64,1}:
 1
 3

In [63]:
setdiff(b,a) # returns 4,5

2-element Array{Int64,1}:
 4
 5

In [64]:
a = [1 2; 3 4] # create a 2x2 matrix

2×2 Array{Int64,2}:
 1  2
 3  4

In [65]:
a[2, 2] # access element 2,2

4

In [66]:
a[1, :] # access first row

2-element Array{Int64,1}:
 1
 2

In [67]:
a[2, 5] # access element 2,2

BoundsError: BoundsError: attempt to access 2×2 Array{Int64,2} at index [2, 5]

In [68]:
a[:, 1] # access first column

2-element Array{Int64,1}:
 1
 3

In [69]:
a = zeros(2,2) # zero matrix

2×2 Array{Float64,2}:
 0.0  0.0
 0.0  0.0

In [70]:
a = ones(2,2) # unitary matrix

2×2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0

In [71]:
a = fill(2,3,4) # fill a 3x4 matrix with 2's

3×4 Array{Int64,2}:
 2  2  2  2
 2  2  2  2
 2  2  2  2

In [72]:
a = trues(2,2) # 2x2 matrix of trues

2×2 BitArray{2}:
 true  true
 true  true

In [73]:
a = falses(2,2) # 2x2 matrix of falses

2×2 BitArray{2}:
 false  false
 false  false

In [74]:
a = rand(2,2) # random matrix (uniform)

2×2 Array{Float64,2}:
 0.0129514  0.270385
 0.265078   0.88472 

In [75]:
a = randn(2,2) # random matrix (gaussian)

2×2 Array{Float64,2}:
  0.0204689  -2.02295
 -0.0329929   1.02578